Question 1

In [3]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Question 2

In [8]:
import numpy as np
lst_1=[]
lst_2=[]
for i in range(5):
    x=int(input("\nEnter the value for lst_1: "))
    lst_1.append(x)
for i in range(5):
    x=int(input("\nEnter the value for lst_2: "))
    lst_2.append(x)
arr_1=np.array(lst_1)
arr_2=np.array(lst_2)
arr=np.concatenate((arr_1,arr_2))
print("\nArray value for concatenated arr:",arr)
sortarr=np.sort(arr)
print("\nSorted array for concatenated arr:",sortarr)


Enter the value for lst_1: 1

Enter the value for lst_1: 0

Enter the value for lst_1: 9

Enter the value for lst_1: 2

Enter the value for lst_1: 8

Enter the value for lst_2: 3

Enter the value for lst_2: 4

Enter the value for lst_2: 7

Enter the value for lst_2: 6

Enter the value for lst_2: 5

Array value for concatenated arr: [1 0 9 2 8 3 4 7 6 5]

Sorted array for concatenated arr: [0 1 2 3 4 5 6 7 8 9]


Question 3

In [9]:
import numpy as np
arr=np.array([[3,4,6,7,8],[2,3,4,7,9]])
print(arr.ndim)
print(arr.size)

2
10


Question 4

In [10]:
import numpy as np
arr=np.arange(12)
print(arr.shape)
row_arr=arr[np.newaxis,:]
print("\nShape of 2d Array in row major:",row_arr.shape)
col_arr=arr[:,np.newaxis]
print("\nShape of 2d Array in column major:",col_arr.shape)


(12,)

Shape of 2d Array in row major: (1, 12)

Shape of 2d Array in column major: (12, 1)


Question 5


In [11]:
import numpy as np
arr_1=np.square([1,2,3,4,5])
arr_2=np.square([6,7,8,9,10])
print("\nHorizontal Append:",np.hstack((arr_1,arr_2)))
print("\nVertical Append:",np.vstack((arr_1,arr_2)))





Horizontal Append: [  1   4   9  16  25  36  49  64  81 100]

Vertical Append: [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


Question 6


In [12]:
import numpy as np
arr_1=np.array([1,4,9,16,25,1,4,2,3,2,5,6,5,7,8,10])
unique,counts=np.unique(arr_1,return_counts=True)
arr=np.asarray((unique,counts)).T
print(arr)

[[ 1  2]
 [ 2  2]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  1]
 [10  1]
 [16  1]
 [25  1]]
